/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class AppTest {
    @Test
    fun appHasAGreeting() {

    }
}
